export class Texts {
    //PORT
    static readonly IN: string = 'IN'
    static readonly OUT: string = 'OUT'
    static readonly WHITE: string = 'WHITE'
    static readonly SPACECODEADMIN: string = 'SPACECODEADMIN'
    static readonly COMPANYADMIN: string = 'COMPANYADMIN'
    static readonly companyId: string = 'companyId'
    static readonly skuId_companyId: string = 'skuId.companyId'
    static readonly fingerPrint: string = 'fingerPrint'
    static readonly CONNECTION: string = 'connection'
    static readonly INVENTORY: string = 'INVENTORY'
    static readonly accessDrawer: string = 'accessDrawer'
    static readonly rawActivityResponse: string = 'rawActivityResponse'
    static readonly accessedDrawer: string = 'accessedDrawer'
    static readonly accessDrawerWithBadge: string = 'accessDrawerWithBadge'
    static readonly registerDevice: string = 'registerDevice'
    static readonly deviceCommand: string = 'deviceCommand'
    static readonly YOUR_SOCKET_ID: string = 'Your socket id'
    static readonly createRawActivity: string = 'createRawActivity'
    static readonly diamondMatch: string = 'diamondMatch'
    static readonly triggeredLed: string = 'triggeredLed'
    static readonly disconnect: string = 'disconnect'
    static readonly createRawActivityAsync: string = 'createRawActivityAsync'
    static readonly diamondMatchRegistration: string = 'diamondMatchRegistration'
    static readonly triggeredLedResponse: string = 'triggeredLedResponse'
    static readonly string: string = 'string'
    static readonly Success: string = 'Success'
    static readonly success: string = 'success'
    static readonly Failure: string = 'Failure'
    static readonly failure: string = 'failure'
    static readonly WELCOME: string = 'Welcome'
    static readonly WELCOME_TO_SPACECODE: string = 'Welcome to Spacecode'
}
